name: Plan and deploy PEP-Web to staging

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-deploy
  cancel-in-progress: true

jobs:
  infrastructure:
    uses: jordanallen-dev/reusable-terraform-workflow/.github/workflows/terraform.yml@main
    with:
      module-path: infra/staging
      apply-environment: staging
      node-version: 16.0.0
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENV_VARS: "TF_VAR_mysql_username=${{ secrets.MYSQL_USERNAME }}\n\
        TF_VAR_mysql_password=${{ secrets.MYSQL_PASSWORD }}\n\
        TF_VAR_archive_threshold_days=${{ vars.ARCHIVE_THRESHOLD_DAYS }}\n\
        TF_VAR_host=${{ vars.EC2_HOSTNAME }}\n\
        TF_VAR_mysql_host=${{ vars.MYSQL_HOSTNAME }}\n\
        TF_VAR_mysql_schema=${{ vars.MYSQL_SCHEMA }}\n\
        TF_VAR_pem_key=${{ vars.PEM_KEY_PATH }}\n\
        TF_VAR_s3_bucket=${{ vars.PEM_KEY_BUCKET }}\n\
        TF_VAR_username=${{ vars.EC2_USERNAME }}\n\
        TF_VAR_utilities_url=${{ vars.UTILITIES_URL }}"
