name: Plan and deploy PEP-Web to staging

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-deploy
  cancel-in-progress: true

jobs:
  env:
    name: "Setup dynamic environment variables"
    runs-on: ubuntu-latest
    outputs:
      archive_threshold_days: ${{ steps.set-outputs.outputs.archive_threshold_days}}
    steps:
      - name: Set output
        id: set-outputs
        run: |
          echo "archive_threshold_days=${{ vars.ARCHIVE_THRESHOLD_DAYS }}" >> $GITHUB_OUTPUT

  infrastructure:
    uses: jordanallen-dev/reusable-terraform-workflow/.github/workflows/terraform.yml@main
    with:
      module-path: infra/staging
      apply-environment: staging
      node-version: 16.0.0
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENV_VARS: "TF_VAR_mysql_username=${{ secrets.MYSQL_USERNAME }}\n\
        TF_VAR_mysql_password=${{ secrets.MYSQL_PASSWORD }}\n\
        TF_VAR_archive_threshold_days=${{ needs.env.outputs.archive_threshold_days }}"
